steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js', '.']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args: ['push', 'asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'clouddeploy-config'
  args:
  - bash
  - -c
  - |
    gcloud deploy apply --file=delivery-pipeline.yaml --region=asia-east1
    gcloud deploy apply --file=target-test.yaml --region=asia-east1
    gcloud deploy apply --file=target-staging.yaml --region=asia-east1
    gcloud deploy apply --file=target-prod.yaml --region=asia-east1
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'deploy'
  - 'releases'
  - 'create'
  - 'release-${SHORT_SHA}'
  - '--delivery-pipeline=hello-js'
  - '--region=asia-east1'
  - '--annotations=commitId=${REVISION_ID}'
  - '--source=.' 
  - '--skaffold-file=./app-config/skaffold.yaml'
  - '--images=hello-js=asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js:${SHORT_SHA}'

# 部署到測試環境
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'deploy'
  - 'releases'
  - 'promote'
  - '--release=release-${SHORT_SHA}'
  - '--delivery-pipeline=hello-js'
  - '--region=asia-east1'
  - '--to-target=test-cloudrun'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'deploy'
  - 'releases'
  - 'promote'
  - '--release=release-${SHORT_SHA}'
  - '--delivery-pipeline=hello-js'
  - '--region=asia-east1'
  - '--to-target=staging-cloudrun'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'deploy'
  - 'releases'
  - 'promote'
  - '--release=release-${SHORT_SHA}'
  - '--delivery-pipeline=hello-js'
  - '--region=asia-east1'
  - '--to-target=prod-cloudrun'
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'gcloud'
#   args: 
#     - 'run'
#     - 'deploy'
#     - 'your-service-name'
#     - '--image'
#     - 'asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js'
#     - '--region'
#     - 'asia-east1'
#     - '--platform'
#     - 'managed'
#   env:
#   - 'GOOGLE_CLOUD_PROJECT=terraform-429505'
# - name: 'gcr.io/k8s-skaffold/skaffold:latest'
#   entrypoint: 'skaffold'
#   dir: 'app-config'
#   args: ['deploy', '-p', 'test']
#   env:
#   - 'GOOGLE_CLOUD_PROJECT=terraform-429505'

# - name: 'gcr.io/k8s-skaffold/skaffold:latest'
#   entrypoint: 'skaffold'
#   dir: 'app-config'
#   args: ['deploy', '-p', 'staging']
#   env:
#   - 'GOOGLE_CLOUD_PROJECT=terraform-429505'

# - name: 'gcr.io/k8s-skaffold/skaffold:latest'
#   entrypoint: 'skaffold'
#   dir: 'app-config'
#   args: ['deploy', '-p', 'prod']
#   env:
#   - 'GOOGLE_CLOUD_PROJECT=terraform-429505'
#
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
