steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js']
images:
- 'asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
