apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-js-staging
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      serviceAccountName: cd-tut-run-sa@terraform-429505.iam.gserviceaccount.com
      containers:
      - name: hello-js
        image: asia-east1-docker.pkg.dev/terraform-429505/my-registry/hello-js
        env:
          - name: NAME
            value: "Staging"
